openapi: 3.0.1
info:
  title: "Ecosyste.ms: Advisories"
  description: "An open API service providing security vulnerability metadata for many open source software ecosystems."
  contact:
    name: Ecosyste.ms
    email: support@ecosyste.ms
    url: https://ecosyste.ms 
  version: 1.0.0
  license:
    name: CC-BY-SA-4.0
    url: https://creativecommons.org/licenses/by-sa/4.0/
externalDocs:
  description: GitHub Repository
  url: https://github.com/ecosyste-ms/advisories
servers:
- url: https://advisories.ecosyste.ms/api/v1
paths: